export const mapsCatalog = [
  {
    id: 'planisferio',
    name: 'Planisferio',
    thumbnailUrl: '/maps/thumbnails/MapaEscolar000_Planisferio_2000x2500.png',
    imagePath: '/maps/MapaEscolar000_Planisferio_2000x2500.png',
    imageUrl: 'https://mapasescolares.ign.gob.ar/images/mapas/MapaEscolar000_Planisferio_2000x2500.png',
    category: 'otros'
  },
  {
    id: 'america',
    name: 'Mapa de América',
    thumbnailUrl: '/maps/thumbnails/MapaEscolar000_America_2000x2500.png',
    imagePath: '/maps/MapaEscolar000_America_2000x2500.png',
    imageUrl: 'https://mapasescolares.ign.gob.ar/images/mapas/MapaEscolar000_America_2000x2500.png',
    category: 'otros'
  },
  {
    id: 'argentina',
    name: 'Mapa de Argentina Bicontinental',
    thumbnailUrl: '/maps/thumbnails/MapaEscolar000_ArgentinaBicontinental_2000x2500.png',
    imagePath: '/maps/MapaEscolar000_ArgentinaBicontinental_2000x2500.png',
    imageUrl: 'https://mapasescolares.ign.gob.ar/images/mapas/MapaEscolar000_ArgentinaBicontinental_2000x2500.png',
    category: 'otros'
  },
  {
    id: 'antartida',
    name: 'Mapa de Antártida',
    thumbnailUrl: '/maps/thumbnails/MapaEscolar001_Antartida_2000x2500.png',
    imagePath: '/maps/MapaEscolar001_Antartida_2000x2500.png',
    imageUrl: 'https://mapasescolares.ign.gob.ar/images/mapas/MapaEscolar001_Antartida_2000x2500.png',
    category: 'otros'
  },
  {
    id: 'malvinas',
    name: 'Islas Malvinas',
    thumbnailUrl: '/maps/thumbnails/MapaEscolar021_IslasMalvinas_2500x2000.png',
    imagePath: '/maps/MapaEscolar021_IslasMalvinas_2500x2000.png',
    imageUrl: 'https://mapasescolares.ign.gob.ar/images/mapas/MapaEscolar021_IslasMalvinas_2500x2000.png',
    category: 'otros'
  },
  {
    id: 'amba',
    name: 'AMBA - Área Metropolitana Buenos Aires',
    thumbnailUrl: '/maps/thumbnails/MapaEscolar000_AMBA_2000x2500.png',
    imagePath: '/maps/MapaEscolar000_AMBA_2000x2500.png',
    imageUrl: 'https://mapasescolares.ign.gob.ar/images/mapas/MapaEscolar000_AMBA_2000x2500.png',
    category: 'otros'
  },
  {
    id: 'buenos-aires',
    name: 'Provincia de Buenos Aires',
    thumbnailUrl: '/maps/thumbnails/MapaEscolar002_BsAs_2000x2500.png',
    imagePath: '/maps/MapaEscolar002_BsAs_2000x2500.png',
    imageUrl: 'https://mapasescolares.ign.gob.ar/images/mapas/MapaEscolar002_BsAs_2000x2500.png',
    category: 'provincia'
  },
  {
    id: 'cordoba',
    name: 'Provincia de Córdoba',
    thumbnailUrl: '/maps/thumbnails/MapaEscolar005_Cordoba_2000x2500.png',
    imagePath: '/maps/MapaEscolar005_Cordoba_2000x2500.png',
    imageUrl: 'https://mapasescolares.ign.gob.ar/images/mapas/MapaEscolar005_Cordoba_2000x2500.png',
    category: 'provincia',
  },
  {
    id: 'santa-fe',
    name: 'Provincia de Santa Fe',
    thumbnailUrl: '/maps/thumbnails/MapaEscolar014_SantaFe_2000x2500.png',
    imagePath: '/maps/MapaEscolar014_SantaFe_2000x2500.png',
    imageUrl: 'https://mapasescolares.ign.gob.ar/images/mapas/MapaEscolar014_SantaFe_2000x2500.png',
    category: 'provincia',
  },
  {
    id: 'caba',
    name: 'Ciudad Autónoma de Buenos Aires',
    thumbnailUrl: '/maps/thumbnails/MapaEscolar018_CABA_2000x2500.png',
    imagePath: '/maps/MapaEscolar018_CABA_2000x2500.png',
    imageUrl: 'https://mapasescolares.ign.gob.ar/images/mapas/MapaEscolar018_CABA_2000x2500.png',
    category: 'provincia',
  },
  {
    id: 'jujuy',
    name: 'Provincia de Jujuy',
    thumbnailUrl: '/maps/thumbnails/MapaEscolar022_Jujuy_2500x2000.png',
    imagePath: '/maps/MapaEscolar022_Jujuy_2500x2000.png',
    imageUrl: 'https://mapasescolares.ign.gob.ar/images/mapas/MapaEscolar022_Jujuy_2500x2000.png',
    category: 'provincia',
  },
  {
    id: 'salta',
    name: 'Provincia de Salta',
    thumbnailUrl: '/maps/thumbnails/MapaEscolar023_Salta_2500x2000.png',
    imagePath: '/maps/MapaEscolar023_Salta_2500x2000.png',
    imageUrl: 'https://mapasescolares.ign.gob.ar/images/mapas/MapaEscolar023_Salta_2500x2000.png',
    category: 'provincia',
  },
  {
    id: 'mendoza',
    name: 'Provincia de Mendoza',
    thumbnailUrl: '/maps/thumbnails/MapaEscolar009_Mendoza_2000x2500.png',
    imagePath: '/maps/MapaEscolar009_Mendoza_2000x2500.png',
    imageUrl: 'https://mapasescolares.ign.gob.ar/images/mapas/MapaEscolar009_Mendoza_2000x2500.png',
    category: 'provincia',
  },
  {
    id: 'misiones',
    name: 'Provincia de Misiones',
    thumbnailUrl: '/maps/thumbnails/MapaEscolar010_Misiones_2000x2500.png',
    imagePath: '/maps/MapaEscolar010_Misiones_2000x2500.png',
    imageUrl: 'https://mapasescolares.ign.gob.ar/images/mapas/MapaEscolar010_Misiones_2000x2500.png',
    category: 'provincia',
  },
  {
    id: 'tierra-del-fuego',
    name: 'Provincia de Tierra del Fuego',
    thumbnailUrl: '/maps/thumbnails/MapaEscolar000_TIerraDelFuego_2000x2500.png',
    imagePath: '/maps/MapaEscolar000_TIerraDelFuego_2000x2500.png',
    imageUrl: 'https://mapasescolares.ign.gob.ar/images/mapas/MapaEscolar000_TIerraDelFuego_2000x2500.png',
    category: 'provincia',
  },
  {
    id: 'corrientes',
    name: 'Provincia de Corrientes',
    thumbnailUrl: '/maps/thumbnails/MapaEscolar019_Corrientes_2500x2000.png',
    imagePath: '/maps/MapaEscolar019_Corrientes_2500x2000.png',
    imageUrl: 'https://mapasescolares.ign.gob.ar/images/mapas/MapaEscolar019_Corrientes_2500x2000.png',
    category: 'provincia',
  },
  {
    id: 'chaco',
    name: 'Provincia del Chaco',
    thumbnailUrl: '/maps/thumbnails/MapaEscolar004_Chaco_2000x2500.png',
    imagePath: '/maps/MapaEscolar004_Chaco_2000x2500.png',
    imageUrl: 'https://mapasescolares.ign.gob.ar/images/mapas/MapaEscolar004_Chaco_2000x2500.png',
    category: 'provincia',
  },
  {
    id: 'formosa',
    name: 'Provincia de Formosa',
    thumbnailUrl: '/maps/thumbnails/MapaEscolar020_Formosa_2500x2000.png',
    imagePath: '/maps/MapaEscolar020_Formosa_2500x2000.png',
    imageUrl: 'https://mapasescolares.ign.gob.ar/images/mapas/MapaEscolar020_Formosa_2500x2000.png',
    category: 'provincia',
  },
  {
    id: 'santiago-del-estero',
    name: 'Provincia de Santiago del Estero',
    thumbnailUrl: '/maps/thumbnails/MapaEscolar016_SantiagoDelEstero_2000x2500.png',
    imagePath: '/maps/MapaEscolar016_SantiagoDelEstero_2000x2500.png',
    imageUrl: 'https://mapasescolares.ign.gob.ar/images/mapas/MapaEscolar016_SantiagoDelEstero_2000x2500.png',
    category: 'provincia',
  },
  {
    id: 'tucuman',
    name: 'Provincia de Tucumán',
    thumbnailUrl: '/maps/thumbnails/MapaEscolar017_Tucuman_2000x2500.png ',
    imagePath: '/maps/MapaEscolar017_Tucuman_2000x2500.png',
    imageUrl: 'https://mapasescolares.ign.gob.ar/images/mapas/MapaEscolar017_Tucuman_2000x2500.png',
    category: 'provincia',
  },
  {
    id: 'catamarca',
    name: 'Provincia de Catamarca',
    thumbnailUrl: '/maps/thumbnails/MapaEscolar003_Catamarca_2000x2500.png',
    imagePath: '/maps/MapaEscolar003_Catamarca_2000x2500.png',
    imageUrl: 'https://mapasescolares.ign.gob.ar/images/mapas/MapaEscolar003_Catamarca_2000x2500.png',
    category: 'provincia',
  },
  {
    id: 'la-rioja',
    name: 'Provincia de La Rioja',
    thumbnailUrl: '/maps/thumbnails/MapaEscolar008_LaRioja_2000x2500.png',
    imagePath: '/maps/MapaEscolar008_LaRioja_2000x2500.png',
    imageUrl: 'https://mapasescolares.ign.gob.ar/images/mapas/MapaEscolar008_LaRioja_2000x2500.png',
    category: 'provincia',
  },
  {
    id: 'san-juan',
    name: 'Provincia de San Juan',
    thumbnailUrl: '/maps/thumbnails/MapaEscolar012_SanJuan_2000x2500.png',
    imagePath: '/maps/MapaEscolar012_SanJuan_2000x2500.png',
    imageUrl: 'https://mapasescolares.ign.gob.ar/images/mapas/MapaEscolar012_SanJuan_2000x2500.png',
    category: 'provincia',
  },
  {
    id: 'san-luis',
    name: 'Provincia de San Luis',
    thumbnailUrl: '/maps/thumbnails/MapaEscolar013_SanLuis_2000x2500.png',
    imagePath: '/maps/MapaEscolar013_SanLuis_2000x2500.png',
    imageUrl: 'https://mapasescolares.ign.gob.ar/images/mapas/MapaEscolar013_SanLuis_2000x2500.png',
    category: 'provincia',
  },
  {
    id: 'neuquen',
    name: 'Provincia de Neuquén',
    thumbnailUrl: '/maps/thumbnails/MapaEscolar011_Neuquén_2000x2500.png',
    imagePath: '/maps/MapaEscolar011_Neuquén_2000x2500.png',
    imageUrl: 'https://mapasescolares.ign.gob.ar/images/mapas/MapaEscolar011_Neuquén_2000x2500.png',
    category: 'provincia',
  },
  {
    id: 'rio-negro',
    name: 'Provincia de Río Negro',
    thumbnailUrl: '/maps/thumbnails/MapaEscolar023_RioNegro_2500x2000.png',
    imagePath: '/maps/MapaEscolar023_RioNegro_2500x2000.png',
    imageUrl: 'https://mapasescolares.ign.gob.ar/images/mapas/MapaEscolar023_RioNegro_2500x2000.png',
    category: 'provincia',
  },
  {
    id: 'chubut',
    name: 'Provincia de Chubut',
    thumbnailUrl: '/maps/thumbnails/MapaEscolar018_Chubut_2500x2000.png',
    imagePath: '/maps/MapaEscolar018_Chubut_2500x2000.png',
    imageUrl: 'https://mapasescolares.ign.gob.ar/images/mapas/MapaEscolar018_Chubut_2500x2000.png',
    category: 'provincia',
  },
  {
    id: 'santa-cruz',
    name: 'Provincia de Santa Cruz',
    thumbnailUrl: '/maps/thumbnails/MapaEscolar015_SantaCruz_2000x2500.png',
    imagePath: '/maps/MapaEscolar015_SantaCruz_2000x2500.png',
    imageUrl: 'https://mapasescolares.ign.gob.ar/images/mapas/MapaEscolar015_SantaCruz_2000x2500.png',
    category: 'provincia',
  },
  {
    id: 'entre-rios',
    name: 'Provincia de Entre Ríos',
    thumbnailUrl: '/maps/thumbnails/MapaEscolar006_EntreRios_2000x2500.png',
    imagePath: '/maps/MapaEscolar006_EntreRios_2000x2500.png',
    imageUrl: 'https://mapasescolares.ign.gob.ar/images/mapas/MapaEscolar006_EntreRios_2000x2500.png',
    category: 'provincia',
  },
  {
    id: 'la-pampa',
    name: 'Provincia de La Pampa',
    thumbnailUrl: '/maps/thumbnails/MapaEscolar007_LaPampa_2000x2500.png',
    imagePath: '/maps/MapaEscolar007_LaPampa_2000x2500.png',
    imageUrl: 'https://mapasescolares.ign.gob.ar/images/mapas/MapaEscolar007_LaPampa_2000x2500.png',
    category: 'provincia',
  }

]
